### ISSUE TITLE
동명이인 의안정보 누락문제

### ISSUE THREAD

**Issue by JaeyoungKim-HCIL** [snuhci2017/AAA#1]
동명이인에 대해 datasource에서 data가 누락된 문제가 있음 (e.g. 영등포구갑 김영주 의원, 은평구갑 이미경 의원)
이런 사람들의 경우 다시 크롤링해서 처리를 하기에는 시간이 부족하므로 manual하게 처리를 해줘야할듯 함.

실수로 다른 계정으로 Issue Open 해버렸음; (dimlightray = tearofsprit)

**Comment by jaeyoungkim-cs** [comment]
처리완료 billByProposer 파일에 관련 내용 반영 필요.
